### ISSUE TITLE
configuring without in-source

### ISSUE THREAD

**Issue by bsr203** [yatesco/reason-storybook-example#1]
Hi,

I use `https://github.com/reasonml-community/reason-scripts as a boilerplate`, and wondering a way to configure `storybook`. With `reason-scripts` all src files are compiled to lib folder. I also prefer not to have the generated/compiled js files on the src folder. I am not sure how to configure the bs compiler not to include stories when building the app (yarn build), and include all when building stories. Any pointers appreciated.

thank you for the help,
bsr

**Comment by yatesco** [comment]
Hi @bsr203, unfortunately I am no longer working with `reasonml` so I don't really have much help to give. I would say though, that if you are using `reason-scripts` then you _have_ to pretty much follow their strongly opinionated layout.

I did have a few sandboxes where I didn't use `reason-scripts`, which gives you a whole load of control but also loses the _huge_ amount of work that `reason-scripts` do for you.

My advice? Live with the pain and fight more interesting Yaks :-).

You might also find https://coliny.gitbooks.io/reasonml-developer-handbook/content/ useful?

**Comment by bsr203** [comment]
:-) . thank you for the quick response. I in fact saw your notes, and thanks for sharing them. will keep trying :-)
